import {
  Cpo,
  CpoProtocol,
  CpoIntegrationStatus,
  Location,
  Connector,
  ConnectorType,
  PowerType,
  ConnectorStatus,
  FreshnessState,
  Vehicle,
  ChargingSession,
  SessionStatus,
  ChargeTarget
} from '@chargemesh/shared-types';

export const mockCpos: Record<string, Cpo> = {
  'cpo-tata': {
    id: 'cpo-tata',
    name: 'Tata Power EZ Charge',
    partyId: 'TP',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-209-5161',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-statiq': {
    id: 'cpo-statiq',
    name: 'Statiq EV Network',
    partyId: 'SQ',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '+91-9876543210',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-jiobp': {
    id: 'cpo-jiobp',
    name: 'Jio-bp pulse',
    partyId: 'JB',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-891-9023',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
};

export interface StationWithDetails extends Location {
  cpo: Cpo;
  connectors: Connector[];
  distanceKm: number;
  availableCount: number;
  totalConnectors: number;
  tariffPerKwh: number;
  maxPowerKw: number;
}

export const mockStations: StationWithDetails[] = [
  {
    id: 'loc-okhla',
    cpoId: 'cpo-tata',
    externalId: 'TP-OKH-001',
    name: 'Tata Power — Okhla Phase 3 Hub',
    address: 'Plot 42, Okhla Industrial Area Phase III, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'IN',
    postalCode: '110020',
    coordinates: { latitude: 28.5355, longitude: 77.2650 },
    distanceKm: 1.2,
    openingTimes: '24x7 Open',
    facilities: ['Cafe', 'Restroom', 'WiFi', 'EV Lounge'],
    directions: 'Next to Crown Plaza Hotel, basement charging bay',
    lastUpdated: new Date(Date.now() - 25 * 1000).toISOString(), // 25s ago
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 18.5,
    maxPowerKw: 60,
    availableCount: 2,
    totalConnectors: 4,
    connectors: [
      {
        id: 'conn-1',
        evseId: 'evse-1',
        externalId: 'TP-OKH-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date(Date.now() - 25 * 1000).toISOString(),
        dataAgeSeconds: 25,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-2',
        evseId: 'evse-1',
        externalId: 'TP-OKH-C2',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date(Date.now() - 25 * 1000).toISOString(),
        dataAgeSeconds: 25,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-3',
        evseId: 'evse-2',
        externalId: 'TP-OKH-C3',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 30,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date(Date.now() - 40 * 1000).toISOString(),
        dataAgeSeconds: 40,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-4',
        evseId: 'evse-2',
        externalId: 'TP-OKH-C4',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.UNKNOWN, // Non-negotiable test case!
        freshnessState: FreshnessState.UNKNOWN,
        dataAgeSeconds: 720,
        lastUpdated: new Date().toISOString(),
      }
    ]
  },
  {
    id: 'loc-cyberhub',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-CYB-004',
    name: 'Statiq — DLF CyberHub Fast Charger',
    address: 'DLF Cyber City, DLF Phase 2, Sector 24, Gurugram',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122002',
    coordinates: { latitude: 28.4950, longitude: 77.0895 },
    distanceKm: 4.8,
    openingTimes: '06:00 AM - 11:30 PM',
    facilities: ['Shopping Mall', 'Food Court', 'Restroom'],
    directions: 'P1 Parking Level, Pillar B-12',
    lastUpdated: new Date(Date.now() - 420 * 1000).toISOString(), // 7 mins ago -> Stale
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 19.0,
    maxPowerKw: 120,
    availableCount: 1,
    totalConnectors: 3,
    connectors: [
      {
        id: 'conn-5',
        evseId: 'evse-3',
        externalId: 'SQ-CYB-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.DELAYED, // Stale status test
        dataAgeSeconds: 420,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-6',
        evseId: 'evse-3',
        externalId: 'SQ-CYB-C2',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.DELAYED,
        dataAgeSeconds: 420,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-7',
        evseId: 'evse-4',
        externalId: 'SQ-CYB-C3',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.UNAVAILABLE,
        freshnessState: FreshnessState.LIVE,
        dataAgeSeconds: 30,
        lastUpdated: new Date().toISOString(),
      }
    ]
  },
  {
    id: 'loc-aerocity',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-AERO-010',
    name: 'Jio-bp pulse — Aerocity Worldmark',
    address: 'Worldmark 1, Asset Area 8, Hospitality District, Aerocity, New Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'IN',
    postalCode: '110037',
    coordinates: { latitude: 28.5504, longitude: 77.1213 },
    distanceKm: 6.5,
    openingTimes: '24x7 Open',
    facilities: ['Restaurants', 'Airport Access', 'Lounge'],
    directions: 'Surface parking area near Gate 2',
    lastUpdated: new Date(Date.now() - 15 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 17.5,
    maxPowerKw: 150,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'conn-8',
        evseId: 'evse-5',
        externalId: 'JB-AERO-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-9',
        evseId: 'evse-5',
        externalId: 'JB-AERO-C2',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-10',
        evseId: 'evse-6',
        externalId: 'JB-AERO-C3',
        type: ConnectorType.CHADEMO,
        powerType: PowerType.DC,
        maxPower: 50,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'conn-11',
        evseId: 'evse-6',
        externalId: 'JB-AERO-C4',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        dataAgeSeconds: 20,
        lastUpdated: new Date().toISOString(),
      }
    ]
  }
];

export const mockDefaultVehicle: Vehicle = {
  id: 'veh-1',
  userId: 'user-default',
  make: 'Tata',
  model: 'Nexon EV',
  variant: 'Max Empowered+',
  connectorTypes: [ConnectorType.CCS2, ConnectorType.TYPE2],
  maxAcPowerKw: 7.2,
  maxDcPowerKw: 50,
  batteryCapacityKwh: 40.5,
  isDefault: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockRecentSessions: ChargingSession[] = [
  {
    id: 'sess-101',
    userId: 'user-default',
    cpoId: 'cpo-tata',
    locationId: 'loc-okhla',
    evseId: 'evse-1',
    connectorId: 'conn-1',
    cpoSessionId: 'TP-SESS-987123',
    status: SessionStatus.COMPLETED,
    chargeTarget: ChargeTarget.AMOUNT,
    chargeTargetValue: 500,
    startTime: new Date(Date.now() - 86400 * 1000 * 2).toISOString(),
    endTime: new Date(Date.now() - 86400 * 1000 * 2 + 35 * 60 * 1000).toISOString(),
    energyKwh: 24.8,
    durationSeconds: 2100,
    finalAmountPaise: 45880,
    idempotencyKey: 'idem-sess-101',
    createdAt: new Date(Date.now() - 86400 * 1000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sess-102',
    userId: 'user-default',
    cpoId: 'cpo-jiobp',
    locationId: 'loc-aerocity',
    evseId: 'evse-5',
    connectorId: 'conn-8',
    cpoSessionId: 'JB-SESS-441209',
    status: SessionStatus.COMPLETED,
    chargeTarget: ChargeTarget.ENERGY,
    chargeTargetValue: 20,
    startTime: new Date(Date.now() - 86400 * 1000 * 5).toISOString(),
    endTime: new Date(Date.now() - 86400 * 1000 * 5 + 28 * 60 * 1000).toISOString(),
    energyKwh: 20.1,
    durationSeconds: 1680,
    finalAmountPaise: 35175,
    idempotencyKey: 'idem-sess-102',
    createdAt: new Date(Date.now() - 86400 * 1000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
