import {
  Cpo,
  CpoProtocol,
  CpoIntegrationStatus,
  Location,
  Connector,
  ConnectorType,
  PowerType,
  ConnectorStatus,
  FreshnessState,
  Vehicle,
  ChargingSession,
  SessionStatus,
  ChargeTarget,
} from '@chargemesh/shared-types';

export const mockCpos: Record<string, Cpo> = {
  'cpo-tata': {
    id: 'cpo-tata',
    name: 'Tata Power EZ Charge',
    partyId: 'TP',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-209-5161',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-jiobp': {
    id: 'cpo-jiobp',
    name: 'Jio-bp pulse',
    partyId: 'JB',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-891-9023',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-statiq': {
    id: 'cpo-statiq',
    name: 'Statiq Grid',
    partyId: 'SQ',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '+91-9876543210',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-chargezone': {
    id: 'cpo-chargezone',
    name: 'ChargeZone',
    partyId: 'CZ',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-120-2223',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-ather': {
    id: 'cpo-ather',
    name: 'Ather Grid',
    partyId: 'AG',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-103-0055',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  'cpo-zeon': {
    id: 'cpo-zeon',
    name: 'Zeon Charging',
    partyId: 'ZC',
    countryCode: 'IN',
    protocol: CpoProtocol.OCPI_2_3,
    integrationStatus: CpoIntegrationStatus.ACTIVE,
    supportPhone: '1800-572-8888',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

export interface StationWithDetails extends Location {
  cpo: Cpo;
  connectors: Connector[];
  distanceKm: number;
  availableCount: number;
  totalConnectors: number;
  tariffPerKwh: number;
  maxPowerKw: number;
  district?: string;
}

export const mockStations: StationWithDetails[] = [
  // ================= TATA POWER =================
  {
    id: 'tp-del-01',
    cpoId: 'cpo-tata',
    externalId: 'TP-OKH-001',
    name: 'Tata Power — Okhla Phase 3 Hub',
    address: 'Plot 42, Okhla Industrial Area Phase III, New Delhi',
    city: 'New Delhi',
    district: 'South East Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110020',
    coordinates: { latitude: 28.5355, longitude: 77.2650 },
    distanceKm: 1.2,
    openingTimes: '24x7 Open',
    facilities: ['Cafe', 'Restroom', 'WiFi', 'EV Lounge'],
    directions: 'Next to Crown Plaza Hotel, basement charging bay',
    lastUpdated: new Date(Date.now() - 25 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 18.5,
    maxPowerKw: 60,
    availableCount: 2,
    totalConnectors: 4,
    connectors: [
      {
        id: 'tp-1-c1',
        evseId: 'evse-tp-1',
        externalId: 'TP-OKH-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date(Date.now() - 25 * 1000).toISOString(),
        dataAgeSeconds: 25,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'tp-1-c2',
        evseId: 'evse-tp-1',
        externalId: 'TP-OKH-C2',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date(Date.now() - 25 * 1000).toISOString(),
        dataAgeSeconds: 25,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'tp-del-02',
    cpoId: 'cpo-tata',
    externalId: 'TP-CP-002',
    name: 'Tata Power — Connaught Place Metro Hub',
    address: 'Block A, Inner Circle, Connaught Place, New Delhi',
    city: 'New Delhi',
    district: 'New Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110001',
    coordinates: { latitude: 28.6328, longitude: 77.2197 },
    distanceKm: 2.8,
    openingTimes: '24x7 Open',
    facilities: ['Shopping', 'Food Court', 'Metro Access', 'Washroom'],
    directions: 'Palika Underground parking entrance Gate 2',
    lastUpdated: new Date(Date.now() - 10 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 20.0,
    maxPowerKw: 120,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'tp-2-c1',
        evseId: 'evse-tp-2',
        externalId: 'TP-CP-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 10,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'tp-2-c2',
        evseId: 'evse-tp-2',
        externalId: 'TP-CP-C2',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 10,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'tp-ggn-03',
    cpoId: 'cpo-tata',
    externalId: 'TP-CYB-003',
    name: 'Tata Power — DLF Cyber Hub Express',
    address: 'DLF Cyber City, Phase 2, Sector 24, Gurugram',
    city: 'Gurugram',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122002',
    coordinates: { latitude: 28.4950, longitude: 77.0895 },
    distanceKm: 8.5,
    openingTimes: '24x7 Open',
    facilities: ['Fine Dining', 'Coffee Shops', 'Valet Parking'],
    directions: 'Cyber Hub Tower B visitor parking level P1',
    lastUpdated: new Date(Date.now() - 40 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 19.0,
    maxPowerKw: 60,
    availableCount: 0,
    totalConnectors: 2,
    connectors: [
      {
        id: 'tp-3-c1',
        evseId: 'evse-tp-3',
        externalId: 'TP-CYB-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 40,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'tp-noid-04',
    cpoId: 'cpo-tata',
    externalId: 'TP-NOI-004',
    name: 'Tata Power — DLF Mall of India Sector 18',
    address: 'Plot M-03, Sector 18, Noida, Uttar Pradesh',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    country: 'IN',
    postalCode: '201301',
    coordinates: { latitude: 28.5672, longitude: 77.3210 },
    distanceKm: 6.2,
    openingTimes: '10:00 AM - 11:00 PM',
    facilities: ['Cinema', 'Food Court', 'Washrooms', 'Valet'],
    directions: 'Mall Basement 2 Pillar D-14 EV Bay',
    lastUpdated: new Date(Date.now() - 15 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 16.5,
    maxPowerKw: 22,
    availableCount: 4,
    totalConnectors: 4,
    connectors: [
      {
        id: 'tp-4-c1',
        evseId: 'evse-tp-4',
        externalId: 'TP-NOI-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'tp-mum-05',
    cpoId: 'cpo-tata',
    externalId: 'TP-BOM-005',
    name: 'Tata Power — Bandra Kurla Complex Hub',
    address: 'G Block, BKC Road, Bandra East, Mumbai',
    city: 'Mumbai',
    district: 'Mumbai Suburban',
    state: 'Maharashtra',
    country: 'IN',
    postalCode: '400051',
    coordinates: { latitude: 19.0657, longitude: 72.8687 },
    distanceKm: 14.0,
    openingTimes: '24x7 Open',
    facilities: ['Financial Hub', 'Restrooms', 'Security'],
    directions: 'BKC Ground Parking near Jio Convention Centre',
    lastUpdated: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-tata'],
    tariffPerKwh: 19.5,
    maxPowerKw: 120,
    availableCount: 4,
    totalConnectors: 4,
    connectors: [
      {
        id: 'tp-5-c1',
        evseId: 'evse-tp-5',
        externalId: 'TP-BOM-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 5,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },

  // ================= JIO-BP PULSE =================
  {
    id: 'jb-aero-01',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-AERO-001',
    name: 'Jio-bp pulse — Aerocity EV Mega Hub',
    address: 'Asset Area 4, Hospitality District, Aerocity, New Delhi',
    city: 'New Delhi',
    district: 'South West Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110037',
    coordinates: { latitude: 28.5502, longitude: 77.1215 },
    distanceKm: 4.5,
    openingTimes: '24x7 Open',
    facilities: ['Wild Bean Cafe', 'Fast Restrooms', 'High-Speed WiFi', '24/7 Security'],
    directions: 'Near Pullman Hotel, dedicated drive-through canopy',
    lastUpdated: new Date(Date.now() - 5 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 21.0,
    maxPowerKw: 150,
    availableCount: 4,
    totalConnectors: 6,
    connectors: [
      {
        id: 'jb-1-c1',
        evseId: 'evse-jb-1',
        externalId: 'JB-AERO-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 5,
        lastUpdated: new Date().toISOString(),
      },
      {
        id: 'jb-1-c2',
        evseId: 'evse-jb-1',
        externalId: 'JB-AERO-C2',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 5,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'jb-wpe-02',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-WPE-002',
    name: 'Jio-bp pulse — Western Peripheral Highway Plaza',
    address: 'KMP Expressway Toll Plaza 14, Manesar Border',
    city: 'Manesar',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122051',
    coordinates: { latitude: 28.3750, longitude: 76.9210 },
    distanceKm: 18.2,
    openingTimes: '24x7 Open',
    facilities: ['Food Court', 'Fuel Station', 'Kids Zone', 'Rest Area'],
    directions: 'Highway Waypoint Plaza Northbound km 48',
    lastUpdated: new Date(Date.now() - 12 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 19.5,
    maxPowerKw: 120,
    availableCount: 2,
    totalConnectors: 2,
    connectors: [
      {
        id: 'jb-2-c1',
        evseId: 'evse-jb-2',
        externalId: 'JB-WPE-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 12,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'jb-gn-03',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-GNE-003',
    name: 'Jio-bp pulse — Greater Noida Expressway Hub',
    address: 'Sector 135, Noida-Greater Noida Expressway, Noida',
    city: 'Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    country: 'IN',
    postalCode: '201304',
    coordinates: { latitude: 28.5020, longitude: 77.4050 },
    distanceKm: 12.0,
    openingTimes: '24x7 Open',
    facilities: ['Convenience Store', 'Coffee Shop', 'ATM'],
    directions: 'Advant Navis Business Park service lane',
    lastUpdated: new Date(Date.now() - 18 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 18.0,
    maxPowerKw: 60,
    availableCount: 1,
    totalConnectors: 4,
    connectors: [
      {
        id: 'jb-3-c1',
        evseId: 'evse-jb-3',
        externalId: 'JB-GNE-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 18,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'jb-dwk-04',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-DWK-004',
    name: 'Jio-bp pulse — Dwarka Sector 10 Metro Bay',
    address: 'Metro Station Parking Complex, Sector 10, Dwarka, New Delhi',
    city: 'New Delhi',
    district: 'South West Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110075',
    coordinates: { latitude: 28.5815, longitude: 77.0580 },
    distanceKm: 9.4,
    openingTimes: '06:00 AM - 11:30 PM',
    facilities: ['Metro Station', 'ATM', 'Snack Kiosk'],
    directions: 'Metro gate 1 surface parking bay',
    lastUpdated: new Date(Date.now() - 35 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 15.0,
    maxPowerKw: 22,
    availableCount: 0,
    totalConnectors: 2,
    connectors: [
      {
        id: 'jb-4-c1',
        evseId: 'evse-jb-4',
        externalId: 'JB-DWK-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 35,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'jb-blr-05',
    cpoId: 'cpo-jiobp',
    externalId: 'JB-BLR-005',
    name: 'Jio-bp pulse — Electronic City Tech Corridor',
    address: 'Hosur Main Road, Electronic City Phase 1, Bengaluru',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    country: 'IN',
    postalCode: '560100',
    coordinates: { latitude: 12.8452, longitude: 77.6602 },
    distanceKm: 18.0,
    openingTimes: '24x7 Open',
    facilities: ['Cafe', 'WiFi', 'Washroom', '24x7 Canopy'],
    directions: 'Next to Infosys Gate 1 Service Road',
    lastUpdated: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-jiobp'],
    tariffPerKwh: 20.0,
    maxPowerKw: 150,
    availableCount: 4,
    totalConnectors: 6,
    connectors: [
      {
        id: 'jb-5-c1',
        evseId: 'evse-jb-5',
        externalId: 'JB-BLR-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 8,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },

  // ================= STATIQ GRID =================
  {
    id: 'sq-amb-01',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-AMB-001',
    name: 'Statiq — Ambience Mall Vasant Kunj',
    address: 'Nelson Mandela Marg, Vasant Kunj, New Delhi',
    city: 'New Delhi',
    district: 'South West Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110070',
    coordinates: { latitude: 28.5410, longitude: 77.1550 },
    distanceKm: 3.4,
    openingTimes: '24x7 Open',
    facilities: ['Cinema', 'Food Court', 'Valet', 'Restrooms', 'Shopping'],
    directions: 'Ambience Mall Basement 1, Pillar 28',
    lastUpdated: new Date(Date.now() - 8 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 19.0,
    maxPowerKw: 120,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'sq-1-c1',
        evseId: 'evse-sq-1',
        externalId: 'SQ-AMB-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 8,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'sq-sel-02',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-SEL-002',
    name: 'Statiq — Select Citywalk Saket',
    address: 'A-3, District Centre, Saket, New Delhi',
    city: 'New Delhi',
    district: 'South Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110017',
    coordinates: { latitude: 28.5284, longitude: 77.2185 },
    distanceKm: 2.1,
    openingTimes: '10:00 AM - 11:30 PM',
    facilities: ['Shopping', 'Starbucks', 'Valet', 'Restrooms'],
    directions: 'Basement P2 Near Escalator lobby',
    lastUpdated: new Date(Date.now() - 20 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 18.0,
    maxPowerKw: 60,
    availableCount: 2,
    totalConnectors: 4,
    connectors: [
      {
        id: 'sq-2-c1',
        evseId: 'evse-sq-2',
        externalId: 'SQ-SEL-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 20,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'sq-wm-03',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-WM-003',
    name: 'Statiq — Worldmark Aerocity Towers',
    address: 'Worldmark 1, Asset 8, Aerocity, New Delhi',
    city: 'New Delhi',
    district: 'South West Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110037',
    coordinates: { latitude: 28.5535, longitude: 77.1235 },
    distanceKm: 4.8,
    openingTimes: '24x7 Open',
    facilities: ['Corporate Cafes', 'Underground Security', 'WiFi'],
    directions: 'Worldmark 1 Basement 2 Executive Bay',
    lastUpdated: new Date(Date.now() - 14 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 16.0,
    maxPowerKw: 22,
    availableCount: 6,
    totalConnectors: 6,
    connectors: [
      {
        id: 'sq-3-c1',
        evseId: 'evse-sq-3',
        externalId: 'SQ-WM-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 14,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'sq-pac-04',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-PAC-004',
    name: 'Statiq — Pacific Mall Tagore Garden',
    address: 'Tagore Garden, Najafgarh Road, Subhash Nagar, New Delhi',
    city: 'New Delhi',
    district: 'West Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110027',
    coordinates: { latitude: 28.6432, longitude: 77.1080 },
    distanceKm: 7.6,
    openingTimes: '10:00 AM - 11:00 PM',
    facilities: ['Shopping', 'Food Court', 'Cinema'],
    directions: 'P1 Parking Lane 4',
    lastUpdated: new Date(Date.now() - 50 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 18.5,
    maxPowerKw: 50,
    availableCount: 0,
    totalConnectors: 2,
    connectors: [
      {
        id: 'sq-4-c1',
        evseId: 'evse-sq-4',
        externalId: 'SQ-PAC-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 50,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 50,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'sq-jpr-05',
    cpoId: 'cpo-statiq',
    externalId: 'SQ-JPR-005',
    name: 'Statiq — MI Road Corporate Plaza',
    address: 'Mirza Ismail Road, C-Scheme, Ashok Nagar, Jaipur',
    city: 'Jaipur',
    district: 'Jaipur',
    state: 'Rajasthan',
    country: 'IN',
    postalCode: '302001',
    coordinates: { latitude: 26.9160, longitude: 75.8050 },
    distanceKm: 22.0,
    openingTimes: '24x7 Open',
    facilities: ['Shopping Area', 'Heritage Dining', 'EV Lounge'],
    directions: 'Near Raj Mandir Cinema complex',
    lastUpdated: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-statiq'],
    tariffPerKwh: 18.0,
    maxPowerKw: 60,
    availableCount: 2,
    totalConnectors: 2,
    connectors: [
      {
        id: 'sq-5-c1',
        evseId: 'evse-sq-5',
        externalId: 'SQ-JPR-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },

  // ================= CHARGEZONE =================
  {
    id: 'cz-jpr-01',
    cpoId: 'cpo-chargezone',
    externalId: 'CZ-JPR-001',
    name: 'ChargeZone — Delhi-Jaipur Highway Fast Corridor',
    address: 'NH-48 Expressway km 68, Bilaspur Chowk, Gurugram',
    city: 'Gurugram',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122413',
    coordinates: { latitude: 28.3240, longitude: 76.8450 },
    distanceKm: 24.5,
    openingTimes: '24x7 Open',
    facilities: ['Highway Dhaba', 'Restrooms', 'EV Charging Lounge', 'Security'],
    directions: 'Main toll service rest stop plaza',
    lastUpdated: new Date(Date.now() - 10 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-chargezone'],
    tariffPerKwh: 22.0,
    maxPowerKw: 180,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'cz-1-c1',
        evseId: 'evse-cz-1',
        externalId: 'CZ-JPR-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 180,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 10,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'cz-agr-02',
    cpoId: 'cpo-chargezone',
    externalId: 'CZ-AGR-002',
    name: 'ChargeZone — Yamuna Expressway SuperHub',
    address: 'Yamuna Expressway Mile 22 Food Plaza, Jewar',
    city: 'Greater Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    country: 'IN',
    postalCode: '203135',
    coordinates: { latitude: 28.2150, longitude: 77.5800 },
    distanceKm: 32.0,
    openingTimes: '24x7 Open',
    facilities: ['McDonalds', 'Costa Coffee', 'Restrooms', 'Fuel'],
    directions: 'Toll Plaza 1 Food Court Parking',
    lastUpdated: new Date(Date.now() - 15 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-chargezone'],
    tariffPerKwh: 21.5,
    maxPowerKw: 150,
    availableCount: 2,
    totalConnectors: 4,
    connectors: [
      {
        id: 'cz-2-c1',
        evseId: 'evse-cz-2',
        externalId: 'CZ-AGR-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'cz-np-03',
    cpoId: 'cpo-chargezone',
    externalId: 'CZ-NP-003',
    name: 'ChargeZone — Nehru Place Corporate Tower',
    address: 'Eros Corporate Tower, Nehru Place, New Delhi',
    city: 'New Delhi',
    district: 'South East Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110019',
    coordinates: { latitude: 28.5490, longitude: 77.2520 },
    distanceKm: 1.8,
    openingTimes: '24x7 Open',
    facilities: ['Bank / ATMs', 'Cafes', 'Metro 100m'],
    directions: 'Eros Tower visitors parking bay',
    lastUpdated: new Date(Date.now() - 25 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-chargezone'],
    tariffPerKwh: 18.0,
    maxPowerKw: 50,
    availableCount: 1,
    totalConnectors: 2,
    connectors: [
      {
        id: 'cz-3-c1',
        evseId: 'evse-cz-3',
        externalId: 'CZ-NP-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 50,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 25,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'cz-gcr-04',
    cpoId: 'cpo-chargezone',
    externalId: 'CZ-GCR-004',
    name: 'ChargeZone — Golf Course Extension Hub',
    address: 'Sector 65, Golf Course Extension Road, Gurugram',
    city: 'Gurugram',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122018',
    coordinates: { latitude: 28.4110, longitude: 77.0680 },
    distanceKm: 11.2,
    openingTimes: '24x7 Open',
    facilities: ['Supermarket', 'Coffee Lounge'],
    directions: 'M3M Urbana commercial plaza surface parking',
    lastUpdated: new Date(Date.now() - 45 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-chargezone'],
    tariffPerKwh: 19.0,
    maxPowerKw: 60,
    availableCount: 0,
    totalConnectors: 2,
    connectors: [
      {
        id: 'cz-4-c1',
        evseId: 'evse-cz-4',
        externalId: 'CZ-GCR-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 60,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 45,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },

  // ================= ATHER GRID =================
  {
    id: 'ag-hkv-01',
    cpoId: 'cpo-ather',
    externalId: 'AG-HKV-001',
    name: 'Ather Grid — Hauz Khas Village Plaza',
    address: 'Hauz Khas Tank Rd, Deer Park, New Delhi',
    city: 'New Delhi',
    district: 'South Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110016',
    coordinates: { latitude: 28.5530, longitude: 77.1940 },
    distanceKm: 3.1,
    openingTimes: '08:00 AM - 11:00 PM',
    facilities: ['Boutique Cafes', 'Lake View', 'Restrooms'],
    directions: 'HKV main gate entrance parking bay',
    lastUpdated: new Date(Date.now() - 12 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-ather'],
    tariffPerKwh: 12.0,
    maxPowerKw: 7.4,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'ag-1-c1',
        evseId: 'evse-ag-1',
        externalId: 'AG-HKV-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_1_PHASE,
        maxPower: 7.4,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 12,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'ag-se-02',
    cpoId: 'cpo-ather',
    externalId: 'AG-SE-002',
    name: 'Ather Grid — South Extension Part 2',
    address: 'Main Market Block E, South Extension II, New Delhi',
    city: 'New Delhi',
    district: 'South Delhi',
    state: 'NCT Of Delhi',
    country: 'IN',
    postalCode: '110049',
    coordinates: { latitude: 28.5680, longitude: 77.2210 },
    distanceKm: 2.5,
    openingTimes: '24x7 Open',
    facilities: ['Shopping Street', 'Food Outlets'],
    directions: 'Behind South Ex Metro Station Exit 3',
    lastUpdated: new Date(Date.now() - 5 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-ather'],
    tariffPerKwh: 15.0,
    maxPowerKw: 22,
    availableCount: 2,
    totalConnectors: 2,
    connectors: [
      {
        id: 'ag-2-c1',
        evseId: 'evse-ag-2',
        externalId: 'AG-SE-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_3_PHASE,
        maxPower: 22,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 5,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'ag-s29-03',
    cpoId: 'cpo-ather',
    externalId: 'AG-S29-003',
    name: 'Ather Grid — Sector 29 Leisure Valley Hub',
    address: 'Sector 29 Commercial Market, Near IFFCO Chowk, Gurugram',
    city: 'Gurugram',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122002',
    coordinates: { latitude: 28.4680, longitude: 77.0630 },
    distanceKm: 9.8,
    openingTimes: '24x7 Open',
    facilities: ['Pubs & Breweries', 'Park View', 'Restrooms'],
    directions: 'Sector 29 central parking circle',
    lastUpdated: new Date(Date.now() - 60 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-ather'],
    tariffPerKwh: 13.5,
    maxPowerKw: 7.4,
    availableCount: 0,
    totalConnectors: 4,
    connectors: [
      {
        id: 'ag-3-c1',
        evseId: 'evse-ag-3',
        externalId: 'AG-S29-C1',
        type: ConnectorType.TYPE2,
        powerType: PowerType.AC_1_PHASE,
        maxPower: 7.4,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 60,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },

  // ================= ZEON CHARGING =================
  {
    id: 'zc-yam-01',
    cpoId: 'cpo-zeon',
    externalId: 'ZC-YAM-001',
    name: 'Zeon — Yamuna Expressway Zero Point',
    address: 'Yamuna Expressway km 0 Interchange, Pari Chowk, Greater Noida',
    city: 'Greater Noida',
    district: 'Gautam Buddha Nagar',
    state: 'Uttar Pradesh',
    country: 'IN',
    postalCode: '201310',
    coordinates: { latitude: 28.4720, longitude: 77.5080 },
    distanceKm: 16.5,
    openingTimes: '24x7 Open',
    facilities: ['Fast Food', 'Clean Restrooms', 'Security Canopy'],
    directions: 'Pari Chowk highway feeder rest point',
    lastUpdated: new Date(Date.now() - 10 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-zeon'],
    tariffPerKwh: 20.0,
    maxPowerKw: 120,
    availableCount: 4,
    totalConnectors: 4,
    connectors: [
      {
        id: 'zc-1-c1',
        evseId: 'evse-zc-1',
        externalId: 'ZC-YAM-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 10,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'zc-man-02',
    cpoId: 'cpo-zeon',
    externalId: 'ZC-MAN-002',
    name: 'Zeon — NH-48 Manesar SuperHub',
    address: 'Sector 8, IMT Manesar, NH-48 Expressway, Gurugram',
    city: 'Manesar',
    district: 'Gurgaon',
    state: 'Haryana',
    country: 'IN',
    postalCode: '122050',
    coordinates: { latitude: 28.3580, longitude: 76.9380 },
    distanceKm: 21.0,
    openingTimes: '24x7 Open',
    facilities: ['Highway Restaurant', 'EV Lounge', 'Free Air & Water'],
    directions: 'Highway km 52 beside Haldirams Drive-Thru',
    lastUpdated: new Date(Date.now() - 15 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-zeon'],
    tariffPerKwh: 21.0,
    maxPowerKw: 150,
    availableCount: 2,
    totalConnectors: 4,
    connectors: [
      {
        id: 'zc-2-c1',
        evseId: 'evse-zc-2',
        externalId: 'ZC-MAN-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 15,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'zc-gt-03',
    cpoId: 'cpo-zeon',
    externalId: 'ZC-GT-003',
    name: 'Zeon — GT Road Murthal Hub',
    address: 'NH-44 Grand Trunk Road, Murthal, Sonipat',
    city: 'Murthal',
    district: 'Sonipat',
    state: 'Haryana',
    country: 'IN',
    postalCode: '131027',
    coordinates: { latitude: 29.0250, longitude: 77.0750 },
    distanceKm: 38.0,
    openingTimes: '24x7 Open',
    facilities: ['Famous Dhabas (Amrik Sukhdev)', 'Restrooms', '24x7 Tea'],
    directions: 'Beside Amrik Sukhdev Dhaba dedicated parking',
    lastUpdated: new Date(Date.now() - 30 * 1000).toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-zeon'],
    tariffPerKwh: 20.5,
    maxPowerKw: 120,
    availableCount: 0,
    totalConnectors: 4,
    connectors: [
      {
        id: 'zc-3-c1',
        evseId: 'evse-zc-3',
        externalId: 'ZC-GT-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 120,
        status: ConnectorStatus.IN_USE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 30,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'zc-ahm-04',
    cpoId: 'cpo-zeon',
    externalId: 'ZC-AHM-004',
    name: 'Zeon — SG Highway Science City Hub',
    address: 'Sarkhej - Gandhinagar Highway, Sola, Ahmedabad',
    city: 'Ahmedabad',
    district: 'Ahmadabad',
    state: 'Gujarat',
    country: 'IN',
    postalCode: '380060',
    coordinates: { latitude: 23.0782, longitude: 72.5122 },
    distanceKm: 16.0,
    openingTimes: '24x7 Open',
    facilities: ['Shopping Plaza', 'Food Zone', 'EV Lounge'],
    directions: 'Science City flyover service road',
    lastUpdated: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cpo: mockCpos['cpo-zeon'],
    tariffPerKwh: 19.5,
    maxPowerKw: 150,
    availableCount: 3,
    totalConnectors: 4,
    connectors: [
      {
        id: 'zc-4-c1',
        evseId: 'evse-zc-4',
        externalId: 'ZC-AHM-C1',
        type: ConnectorType.CCS2,
        powerType: PowerType.DC,
        maxPower: 150,
        status: ConnectorStatus.AVAILABLE,
        freshnessState: FreshnessState.LIVE,
        sourceStatusTimestamp: new Date().toISOString(),
        dataAgeSeconds: 10,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
];

export const mockDefaultVehicle: Vehicle = {
  id: 'veh-1',
  userId: 'user-default',
  make: 'Tata',
  model: 'Nexon EV',
  variant: 'Max Empowered+',
  connectorTypes: [ConnectorType.CCS2, ConnectorType.TYPE2],
  maxAcPowerKw: 7.2,
  maxDcPowerKw: 50,
  batteryCapacityKwh: 40.5,
  isDefault: true,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const mockVehicles: Vehicle[] = [
  mockDefaultVehicle,
  {
    id: 'veh-2',
    userId: 'user-default',
    make: 'MG',
    model: 'ZS EV',
    variant: 'Exclusive Pro',
    connectorTypes: [ConnectorType.CCS2, ConnectorType.TYPE2],
    maxAcPowerKw: 7.4,
    maxDcPowerKw: 75,
    batteryCapacityKwh: 50.3,
    isDefault: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockRecentSessions: ChargingSession[] = [
  {
    id: 'sess-101',
    userId: 'user-default',
    cpoId: 'cpo-tata',
    locationId: 'tp-del-01',
    evseId: 'evse-tp-1',
    connectorId: 'tp-1-c1',
    cpoSessionId: 'TP-SESS-987123',
    status: SessionStatus.COMPLETED,
    chargeTarget: ChargeTarget.AMOUNT,
    chargeTargetValue: 500,
    startTime: new Date(Date.now() - 86400 * 1000 * 2).toISOString(),
    endTime: new Date(Date.now() - 86400 * 1000 * 2 + 35 * 60 * 1000).toISOString(),
    energyKwh: 24.8,
    durationSeconds: 2100,
    finalAmountPaise: 45880,
    idempotencyKey: 'idem-sess-101',
    createdAt: new Date(Date.now() - 86400 * 1000 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sess-102',
    userId: 'user-default',
    cpoId: 'cpo-jiobp',
    locationId: 'jb-aero-01',
    evseId: 'evse-jb-1',
    connectorId: 'jb-1-c1',
    cpoSessionId: 'JB-SESS-441209',
    status: SessionStatus.COMPLETED,
    chargeTarget: ChargeTarget.ENERGY,
    chargeTargetValue: 20,
    startTime: new Date(Date.now() - 86400 * 1000 * 5).toISOString(),
    endTime: new Date(Date.now() - 86400 * 1000 * 5 + 28 * 60 * 1000).toISOString(),
    energyKwh: 20.1,
    durationSeconds: 1680,
    finalAmountPaise: 35175,
    idempotencyKey: 'idem-sess-102',
    createdAt: new Date(Date.now() - 86400 * 1000 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
